# Site settings
title: Pablo Urcola's Research
email: urcola@unizar.es
description: > # this means to ignore newlines until "baseurl:"
  This is the webpage of the research in robotics by Pablo Urcola
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: purcola
github_username:  purcola

# Build settings
markdown: kramdown
permalink: pretty

collections:
  projects:
    output: true
